### PR TITLE
Support lowercase unit ids

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
This makes it easier to view a unit when modifying the URL and pasting an ID from lua.

You can see here the code works as intended: https://3v4l.org/5msGo

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@Rackover

**Comment by louvenarde** [comment]
Oh sorry I didn't see it. Next time ping me on slack or here, else I don't even get a notification.
It's good but isn't it a bit overkill ? You could strtoupper before exploding and get practically the same result, since the commas won't get uppercased. What do you think ?

**Comment by JeroenDeDauw** [comment]
Sure. That is more simple locally. I suspect the reason this did not occur to me is that normally input parsing is done before normalization (and in different functions).

**Comment by louvenarde** [comment]
Just squash your two commits to one so that we don't get one extra "whoopsie" commit and I'll merge straightaway

**Comment by JeroenDeDauw** [comment]
You can do the squash when merging in the web UI

image

**Comment by JeroenDeDauw** [comment]
This randomly popped into my head today: I started wondering why I did not think of this locally simpler solution. I arrived at a definite answer: doing the strtoupper on the whole ids string is the wrong place to do it. The upper-casing is a form of ID normalization which should happen on the ID level. That it is even possible to do so before the input has been parsed (by what happens to be misplaced presentation layer code) is coincidental. Suppose you want to trim the ID strings. And perhaps have some aliasing going on. You cannot do that before the parsing without getting really crazy.

Not that little mixing of responsibilities is going to make a real difference in this code. Just a FYI that I think my original commit is better design wise.

**Comment by louvenarde** [comment]
Well. Your first option is better by design, but when you think of it, the whole PR isn't really even needed. It's cool, it may be useful, but it's nothing needed right now.

**Comment by JeroenDeDauw** [comment]
I outlined the usecase that motivated this change in the description. Not sure what "this is not actually needed" does beyond discouraging people from contributing

**Pull request merged**
